import { NextResponse } from "next/server";
import { API_BASE_URL } from "@/lib/env";

export async function POST(req: Request) {
  const b = (await req.json().catch(() => ({}))) as Record<string, unknown>;

  const res = await fetch(`${API_BASE_URL}/auth/register`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      // Username is server-generated by the worker now; forward it only if a
      // caller still sends one (the web form no longer does).
      ...(b.username ? { username: b.username } : {}),
      // Accept name/full_name/fullName — the web form historically posted `name`,
      // which silently dropped full_name and 400'd every registration.
      full_name: b.full_name ?? b.fullName ?? b.name,
      email: b.email || undefined,
      password: b.password,
      phone: b.phone,
      // Business basics collected in signup step 1 (all optional worker-side).
      company_name: b.company_name ?? undefined,
      business_type_id: b.business_type_id ?? undefined,
      custom_business_type: b.custom_business_type ?? undefined,
      township_id: b.township_id ?? undefined,
    }),
  });
  const data = (await res.json().catch(() => ({}))) as Record<string, unknown>;

  if (!res.ok) {
    return NextResponse.json(
      { error: data.error ?? "Registration failed", reason: data.reason },
      { status: res.status },
    );
  }

  // Account created — trigger the OTP that verify-otp will consume. Keep the
  // request_id: SMSPoh verifies by it, so the OTP step must echo it back.
  const otp = (await fetch(`${API_BASE_URL}/auth/send-otp`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ phone: b.phone }),
  })
    .then((r) => r.json())
    .catch(() => ({}))) as { request_id?: string };

  return NextResponse.json({
    ok: true,
    requiresOtp: true,
    phone: b.phone,
    requestId: otp.request_id,
  });
}
